### ISSUE TITLE
Unable to create a new record for a specific movie

### ISSUE THREAD

**Issue by eldano** [ember-montevideo/movie-manager#1]
When trying to create a new record for this movie: tt1801071(Montevideo, vidimo se!) the browser's console displays an error with the DS.FirebaseAdapter (Error: Assertion Failed: Error: Some errors were encountered while saving movie-manager@model:movie) and the movie doesn't appear on the index.

However, after getting this error and creating another record for a different movie: tt0387564 (Saw) now both movies show up on the index.

I haven't investigated the cause but following the steps above this can be reproduced.

**Comment by san650** [comment]
I couldn't find what's causing the error. 

I think the movies are not being created in the firebase DB and what you see are the cached movies on the client side. Do we have permissions to write to that firebase instance?

**Comment by eldano** [comment]
We do have permissions, the problem is that the attribute tomatoRating for this movie is "N/A" which is parsed as NaN and the adapter can't store it in a numeric type.
I propose storing a -1 for these cases (since a real terrible movie could have a 0), and taking special care of this value when displaying it and calculating the bar width.
I've created a PR #4 for revision.

**Comment by san650** [comment]
Fixed by #4
