### ISSUE TITLE
Various errors showing in console when loading the site

### ISSUE THREAD

**Issue by eldano** [ember-montevideo/movie-manager#2]
When loading the site with content it show different errors related to Content Security Policy directive

example:
[Report Only] Refused to connect to 'http://www.omdbapi.com/?i=tt0387564&tomatoes=true' because it violates the following Content Security Policy directive: "connect-src 'self' ws://localhost:35729 ws://0.0.0.0:35729"

**Comment by san650** [comment]
We have two options:
1. Disable the content security policies (by removing the `ember-cli-content-security-policy` dependency)
2. Register `omdbapi` URLs in the CSP manifest https://github.com/rwjblue/ember-cli-content-security-policy#example

You can try both options, I think configuring the CSP manifest would be a good idea!

**Comment by san650** [comment]
@eldano I've created a PR #3 which adds content security policies for the different sources we're using. 

Please, let me know if this fixes the issues.

**Comment by san650** [comment]
Fixed by #3
